# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hj/Desktop/workspace/cproj/untitled2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hj/Desktop/workspace/cproj/untitled2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"libprotobuf\" \"libprotobuf-lite\" \"libprotoc\" \"protobuf-export\" \"protobuf-headers\" \"protobuf-protos\" \"protoc\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/hj/Desktop/programFiles/ide/clion/clion-2019.2.3/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hj/Desktop/workspace/cproj/untitled2/CMakeFiles /home/hj/Desktop/workspace/cproj/untitled2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hj/Desktop/workspace/cproj/untitled2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libraft

# Build rule for target.
libraft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libraft
.PHONY : libraft

# fast build rule for target.
libraft/fast:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/build
.PHONY : libraft/fast

#=============================================================================
# Target rules for targets named tools

# Build rule for target.
tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools
.PHONY : tools

# fast build rule for target.
tools/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/tools.dir/build.make third_party/grpc/CMakeFiles/tools.dir/build
.PHONY : tools/fast

#=============================================================================
# Target rules for targets named check_epollexclusive

# Build rule for target.
check_epollexclusive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_epollexclusive
.PHONY : check_epollexclusive

# fast build rule for target.
check_epollexclusive/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/check_epollexclusive.dir/build.make third_party/grpc/CMakeFiles/check_epollexclusive.dir/build
.PHONY : check_epollexclusive/fast

#=============================================================================
# Target rules for targets named gen_legal_metadata_characters

# Build rule for target.
gen_legal_metadata_characters: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_legal_metadata_characters
.PHONY : gen_legal_metadata_characters

# fast build rule for target.
gen_legal_metadata_characters/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/gen_legal_metadata_characters.dir/build.make third_party/grpc/CMakeFiles/gen_legal_metadata_characters.dir/build
.PHONY : gen_legal_metadata_characters/fast

#=============================================================================
# Target rules for targets named grpcpp_channelz

# Build rule for target.
grpcpp_channelz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpcpp_channelz
.PHONY : grpcpp_channelz

# fast build rule for target.
grpcpp_channelz/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpcpp_channelz.dir/build.make third_party/grpc/CMakeFiles/grpcpp_channelz.dir/build
.PHONY : grpcpp_channelz/fast

#=============================================================================
# Target rules for targets named grpc++

# Build rule for target.
grpc++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc++
.PHONY : grpc++

# fast build rule for target.
grpc++/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc++.dir/build.make third_party/grpc/CMakeFiles/grpc++.dir/build
.PHONY : grpc++/fast

#=============================================================================
# Target rules for targets named upb

# Build rule for target.
upb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upb
.PHONY : upb

# fast build rule for target.
upb/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/upb.dir/build.make third_party/grpc/CMakeFiles/upb.dir/build
.PHONY : upb/fast

#=============================================================================
# Target rules for targets named grpc_unsecure

# Build rule for target.
grpc_unsecure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_unsecure
.PHONY : grpc_unsecure

# fast build rule for target.
grpc_unsecure/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_unsecure.dir/build.make third_party/grpc/CMakeFiles/grpc_unsecure.dir/build
.PHONY : grpc_unsecure/fast

#=============================================================================
# Target rules for targets named grpc_print_google_default_creds_token

# Build rule for target.
grpc_print_google_default_creds_token: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_print_google_default_creds_token
.PHONY : grpc_print_google_default_creds_token

# fast build rule for target.
grpc_print_google_default_creds_token/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_print_google_default_creds_token.dir/build.make third_party/grpc/CMakeFiles/grpc_print_google_default_creds_token.dir/build
.PHONY : grpc_print_google_default_creds_token/fast

#=============================================================================
# Target rules for targets named grpc_plugin_support

# Build rule for target.
grpc_plugin_support: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_plugin_support
.PHONY : grpc_plugin_support

# fast build rule for target.
grpc_plugin_support/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_plugin_support.dir/build.make third_party/grpc/CMakeFiles/grpc_plugin_support.dir/build
.PHONY : grpc_plugin_support/fast

#=============================================================================
# Target rules for targets named address_sorting

# Build rule for target.
address_sorting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 address_sorting
.PHONY : address_sorting

# fast build rule for target.
address_sorting/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/address_sorting.dir/build.make third_party/grpc/CMakeFiles/address_sorting.dir/build
.PHONY : address_sorting/fast

#=============================================================================
# Target rules for targets named grpc_cronet

# Build rule for target.
grpc_cronet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_cronet
.PHONY : grpc_cronet

# fast build rule for target.
grpc_cronet/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_cronet.dir/build.make third_party/grpc/CMakeFiles/grpc_cronet.dir/build
.PHONY : grpc_cronet/fast

#=============================================================================
# Target rules for targets named grpc++_unsecure

# Build rule for target.
grpc++_unsecure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc++_unsecure
.PHONY : grpc++_unsecure

# fast build rule for target.
grpc++_unsecure/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc++_unsecure.dir/build.make third_party/grpc/CMakeFiles/grpc++_unsecure.dir/build
.PHONY : grpc++_unsecure/fast

#=============================================================================
# Target rules for targets named grpc++_reflection

# Build rule for target.
grpc++_reflection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc++_reflection
.PHONY : grpc++_reflection

# fast build rule for target.
grpc++_reflection/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc++_reflection.dir/build.make third_party/grpc/CMakeFiles/grpc++_reflection.dir/build
.PHONY : grpc++_reflection/fast

#=============================================================================
# Target rules for targets named grpc_ruby_plugin

# Build rule for target.
grpc_ruby_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_ruby_plugin
.PHONY : grpc_ruby_plugin

# fast build rule for target.
grpc_ruby_plugin/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_ruby_plugin.dir/build.make third_party/grpc/CMakeFiles/grpc_ruby_plugin.dir/build
.PHONY : grpc_ruby_plugin/fast

#=============================================================================
# Target rules for targets named tools_cxx

# Build rule for target.
tools_cxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools_cxx
.PHONY : tools_cxx

# fast build rule for target.
tools_cxx/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/tools_cxx.dir/build.make third_party/grpc/CMakeFiles/tools_cxx.dir/build
.PHONY : tools_cxx/fast

#=============================================================================
# Target rules for targets named gen_hpack_tables

# Build rule for target.
gen_hpack_tables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_hpack_tables
.PHONY : gen_hpack_tables

# fast build rule for target.
gen_hpack_tables/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/gen_hpack_tables.dir/build.make third_party/grpc/CMakeFiles/gen_hpack_tables.dir/build
.PHONY : gen_hpack_tables/fast

#=============================================================================
# Target rules for targets named grpc

# Build rule for target.
grpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc
.PHONY : grpc

# fast build rule for target.
grpc/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc.dir/build.make third_party/grpc/CMakeFiles/grpc.dir/build
.PHONY : grpc/fast

#=============================================================================
# Target rules for targets named grpc_csharp_ext

# Build rule for target.
grpc_csharp_ext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_csharp_ext
.PHONY : grpc_csharp_ext

# fast build rule for target.
grpc_csharp_ext/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_csharp_ext.dir/build.make third_party/grpc/CMakeFiles/grpc_csharp_ext.dir/build
.PHONY : grpc_csharp_ext/fast

#=============================================================================
# Target rules for targets named plugins

# Build rule for target.
plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugins
.PHONY : plugins

# fast build rule for target.
plugins/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/plugins.dir/build.make third_party/grpc/CMakeFiles/plugins.dir/build
.PHONY : plugins/fast

#=============================================================================
# Target rules for targets named grpc++_error_details

# Build rule for target.
grpc++_error_details: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc++_error_details
.PHONY : grpc++_error_details

# fast build rule for target.
grpc++_error_details/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc++_error_details.dir/build.make third_party/grpc/CMakeFiles/grpc++_error_details.dir/build
.PHONY : grpc++_error_details/fast

#=============================================================================
# Target rules for targets named grpc_create_jwt

# Build rule for target.
grpc_create_jwt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_create_jwt
.PHONY : grpc_create_jwt

# fast build rule for target.
grpc_create_jwt/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_create_jwt.dir/build.make third_party/grpc/CMakeFiles/grpc_create_jwt.dir/build
.PHONY : grpc_create_jwt/fast

#=============================================================================
# Target rules for targets named gpr

# Build rule for target.
gpr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gpr
.PHONY : gpr

# fast build rule for target.
gpr/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/gpr.dir/build.make third_party/grpc/CMakeFiles/gpr.dir/build
.PHONY : gpr/fast

#=============================================================================
# Target rules for targets named tools_c

# Build rule for target.
tools_c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools_c
.PHONY : tools_c

# fast build rule for target.
tools_c/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/tools_c.dir/build.make third_party/grpc/CMakeFiles/tools_c.dir/build
.PHONY : tools_c/fast

#=============================================================================
# Target rules for targets named gen_percent_encoding_tables

# Build rule for target.
gen_percent_encoding_tables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_percent_encoding_tables
.PHONY : gen_percent_encoding_tables

# fast build rule for target.
gen_percent_encoding_tables/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/gen_percent_encoding_tables.dir/build.make third_party/grpc/CMakeFiles/gen_percent_encoding_tables.dir/build
.PHONY : gen_percent_encoding_tables/fast

#=============================================================================
# Target rules for targets named grpc_cpp_plugin

# Build rule for target.
grpc_cpp_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_cpp_plugin
.PHONY : grpc_cpp_plugin

# fast build rule for target.
grpc_cpp_plugin/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_cpp_plugin.dir/build.make third_party/grpc/CMakeFiles/grpc_cpp_plugin.dir/build
.PHONY : grpc_cpp_plugin/fast

#=============================================================================
# Target rules for targets named grpc_csharp_plugin

# Build rule for target.
grpc_csharp_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_csharp_plugin
.PHONY : grpc_csharp_plugin

# fast build rule for target.
grpc_csharp_plugin/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_csharp_plugin.dir/build.make third_party/grpc/CMakeFiles/grpc_csharp_plugin.dir/build
.PHONY : grpc_csharp_plugin/fast

#=============================================================================
# Target rules for targets named grpc_node_plugin

# Build rule for target.
grpc_node_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_node_plugin
.PHONY : grpc_node_plugin

# fast build rule for target.
grpc_node_plugin/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_node_plugin.dir/build.make third_party/grpc/CMakeFiles/grpc_node_plugin.dir/build
.PHONY : grpc_node_plugin/fast

#=============================================================================
# Target rules for targets named grpc_objective_c_plugin

# Build rule for target.
grpc_objective_c_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_objective_c_plugin
.PHONY : grpc_objective_c_plugin

# fast build rule for target.
grpc_objective_c_plugin/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_objective_c_plugin.dir/build.make third_party/grpc/CMakeFiles/grpc_objective_c_plugin.dir/build
.PHONY : grpc_objective_c_plugin/fast

#=============================================================================
# Target rules for targets named grpc_php_plugin

# Build rule for target.
grpc_php_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_php_plugin
.PHONY : grpc_php_plugin

# fast build rule for target.
grpc_php_plugin/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_php_plugin.dir/build.make third_party/grpc/CMakeFiles/grpc_php_plugin.dir/build
.PHONY : grpc_php_plugin/fast

#=============================================================================
# Target rules for targets named grpc_python_plugin

# Build rule for target.
grpc_python_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_python_plugin
.PHONY : grpc_python_plugin

# fast build rule for target.
grpc_python_plugin/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_python_plugin.dir/build.make third_party/grpc/CMakeFiles/grpc_python_plugin.dir/build
.PHONY : grpc_python_plugin/fast

#=============================================================================
# Target rules for targets named grpc_verify_jwt

# Build rule for target.
grpc_verify_jwt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_verify_jwt
.PHONY : grpc_verify_jwt

# fast build rule for target.
grpc_verify_jwt/fast:
	$(MAKE) -f third_party/grpc/CMakeFiles/grpc_verify_jwt.dir/build.make third_party/grpc/CMakeFiles/grpc_verify_jwt.dir/build
.PHONY : grpc_verify_jwt/fast

#=============================================================================
# Target rules for targets named ahost

# Build rule for target.
ahost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ahost
.PHONY : ahost

# fast build rule for target.
ahost/fast:
	$(MAKE) -f third_party/grpc/third_party/cares/cares/CMakeFiles/ahost.dir/build.make third_party/grpc/third_party/cares/cares/CMakeFiles/ahost.dir/build
.PHONY : ahost/fast

#=============================================================================
# Target rules for targets named adig

# Build rule for target.
adig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adig
.PHONY : adig

# fast build rule for target.
adig/fast:
	$(MAKE) -f third_party/grpc/third_party/cares/cares/CMakeFiles/adig.dir/build.make third_party/grpc/third_party/cares/cares/CMakeFiles/adig.dir/build
.PHONY : adig/fast

#=============================================================================
# Target rules for targets named c-ares

# Build rule for target.
c-ares: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c-ares
.PHONY : c-ares

# fast build rule for target.
c-ares/fast:
	$(MAKE) -f third_party/grpc/third_party/cares/cares/CMakeFiles/c-ares.dir/build.make third_party/grpc/third_party/cares/cares/CMakeFiles/c-ares.dir/build
.PHONY : c-ares/fast

#=============================================================================
# Target rules for targets named acountry

# Build rule for target.
acountry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 acountry
.PHONY : acountry

# fast build rule for target.
acountry/fast:
	$(MAKE) -f third_party/grpc/third_party/cares/cares/CMakeFiles/acountry.dir/build.make third_party/grpc/third_party/cares/cares/CMakeFiles/acountry.dir/build
.PHONY : acountry/fast

#=============================================================================
# Target rules for targets named libprotobuf

# Build rule for target.
libprotobuf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libprotobuf
.PHONY : libprotobuf

# fast build rule for target.
libprotobuf/fast:
	$(MAKE) -f third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/build.make third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/build
.PHONY : libprotobuf/fast

#=============================================================================
# Target rules for targets named protoc

# Build rule for target.
protoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protoc
.PHONY : protoc

# fast build rule for target.
protoc/fast:
	$(MAKE) -f third_party/grpc/third_party/protobuf/CMakeFiles/protoc.dir/build.make third_party/grpc/third_party/protobuf/CMakeFiles/protoc.dir/build
.PHONY : protoc/fast

#=============================================================================
# Target rules for targets named libprotobuf-lite

# Build rule for target.
libprotobuf-lite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libprotobuf-lite
.PHONY : libprotobuf-lite

# fast build rule for target.
libprotobuf-lite/fast:
	$(MAKE) -f third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf-lite.dir/build.make third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf-lite.dir/build
.PHONY : libprotobuf-lite/fast

#=============================================================================
# Target rules for targets named libprotoc

# Build rule for target.
libprotoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libprotoc
.PHONY : libprotoc

# fast build rule for target.
libprotoc/fast:
	$(MAKE) -f third_party/grpc/third_party/protobuf/CMakeFiles/libprotoc.dir/build.make third_party/grpc/third_party/protobuf/CMakeFiles/libprotoc.dir/build
.PHONY : libprotoc/fast

#=============================================================================
# Target rules for targets named global_target

# Build rule for target.
global_target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 global_target
.PHONY : global_target

# fast build rule for target.
global_target/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/CMakeFiles/global_target.dir/build.make third_party/grpc/third_party/boringssl/CMakeFiles/global_target.dir/build
.PHONY : global_target/fast

#=============================================================================
# Target rules for targets named all_tests

# Build rule for target.
all_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_tests
.PHONY : all_tests

# fast build rule for target.
all_tests/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/CMakeFiles/all_tests.dir/build.make third_party/grpc/third_party/boringssl/CMakeFiles/all_tests.dir/build
.PHONY : all_tests/fast

#=============================================================================
# Target rules for targets named crypto_test_data

# Build rule for target.
crypto_test_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypto_test_data
.PHONY : crypto_test_data

# fast build rule for target.
crypto_test_data/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/CMakeFiles/crypto_test_data.dir/build.make third_party/grpc/third_party/boringssl/CMakeFiles/crypto_test_data.dir/build
.PHONY : crypto_test_data/fast

#=============================================================================
# Target rules for targets named boringssl_gtest

# Build rule for target.
boringssl_gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boringssl_gtest
.PHONY : boringssl_gtest

# fast build rule for target.
boringssl_gtest/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/CMakeFiles/boringssl_gtest.dir/build.make third_party/grpc/third_party/boringssl/CMakeFiles/boringssl_gtest.dir/build
.PHONY : boringssl_gtest/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/CMakeFiles/run_tests.dir/build.make third_party/grpc/third_party/boringssl/CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named urandom_test

# Build rule for target.
urandom_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 urandom_test
.PHONY : urandom_test

# fast build rule for target.
urandom_test/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/crypto/CMakeFiles/urandom_test.dir/build.make third_party/grpc/third_party/boringssl/crypto/CMakeFiles/urandom_test.dir/build
.PHONY : urandom_test/fast

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/crypto/CMakeFiles/crypto.dir/build.make third_party/grpc/third_party/boringssl/crypto/CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named crypto_test

# Build rule for target.
crypto_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypto_test
.PHONY : crypto_test

# fast build rule for target.
crypto_test/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/crypto/CMakeFiles/crypto_test.dir/build.make third_party/grpc/third_party/boringssl/crypto/CMakeFiles/crypto_test.dir/build
.PHONY : crypto_test/fast

#=============================================================================
# Target rules for targets named fipsmodule

# Build rule for target.
fipsmodule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fipsmodule
.PHONY : fipsmodule

# fast build rule for target.
fipsmodule/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/build.make third_party/grpc/third_party/boringssl/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/build
.PHONY : fipsmodule/fast

#=============================================================================
# Target rules for targets named boringssl_gtest_main

# Build rule for target.
boringssl_gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boringssl_gtest_main
.PHONY : boringssl_gtest_main

# fast build rule for target.
boringssl_gtest_main/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/crypto/test/CMakeFiles/boringssl_gtest_main.dir/build.make third_party/grpc/third_party/boringssl/crypto/test/CMakeFiles/boringssl_gtest_main.dir/build
.PHONY : boringssl_gtest_main/fast

#=============================================================================
# Target rules for targets named test_support_lib

# Build rule for target.
test_support_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_support_lib
.PHONY : test_support_lib

# fast build rule for target.
test_support_lib/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/crypto/test/CMakeFiles/test_support_lib.dir/build.make third_party/grpc/third_party/boringssl/crypto/test/CMakeFiles/test_support_lib.dir/build
.PHONY : test_support_lib/fast

#=============================================================================
# Target rules for targets named ssl_test

# Build rule for target.
ssl_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssl_test
.PHONY : ssl_test

# fast build rule for target.
ssl_test/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/ssl/CMakeFiles/ssl_test.dir/build.make third_party/grpc/third_party/boringssl/ssl/CMakeFiles/ssl_test.dir/build
.PHONY : ssl_test/fast

#=============================================================================
# Target rules for targets named ssl

# Build rule for target.
ssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssl
.PHONY : ssl

# fast build rule for target.
ssl/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/ssl/CMakeFiles/ssl.dir/build.make third_party/grpc/third_party/boringssl/ssl/CMakeFiles/ssl.dir/build
.PHONY : ssl/fast

#=============================================================================
# Target rules for targets named bssl_shim

# Build rule for target.
bssl_shim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bssl_shim
.PHONY : bssl_shim

# fast build rule for target.
bssl_shim/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/ssl/test/CMakeFiles/bssl_shim.dir/build.make third_party/grpc/third_party/boringssl/ssl/test/CMakeFiles/bssl_shim.dir/build
.PHONY : bssl_shim/fast

#=============================================================================
# Target rules for targets named handshaker

# Build rule for target.
handshaker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 handshaker
.PHONY : handshaker

# fast build rule for target.
handshaker/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/ssl/test/CMakeFiles/handshaker.dir/build.make third_party/grpc/third_party/boringssl/ssl/test/CMakeFiles/handshaker.dir/build
.PHONY : handshaker/fast

#=============================================================================
# Target rules for targets named bssl

# Build rule for target.
bssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bssl
.PHONY : bssl

# fast build rule for target.
bssl/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/tool/CMakeFiles/bssl.dir/build.make third_party/grpc/third_party/boringssl/tool/CMakeFiles/bssl.dir/build
.PHONY : bssl/fast

#=============================================================================
# Target rules for targets named decrepit_test

# Build rule for target.
decrepit_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decrepit_test
.PHONY : decrepit_test

# fast build rule for target.
decrepit_test/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/decrepit/CMakeFiles/decrepit_test.dir/build.make third_party/grpc/third_party/boringssl/decrepit/CMakeFiles/decrepit_test.dir/build
.PHONY : decrepit_test/fast

#=============================================================================
# Target rules for targets named decrepit

# Build rule for target.
decrepit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decrepit
.PHONY : decrepit

# fast build rule for target.
decrepit/fast:
	$(MAKE) -f third_party/grpc/third_party/boringssl/decrepit/CMakeFiles/decrepit.dir/build.make third_party/grpc/third_party/boringssl/decrepit/CMakeFiles/decrepit.dir/build
.PHONY : decrepit/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) -f third_party/grpc/third_party/zlib/CMakeFiles/zlibstatic.dir/build.make third_party/grpc/third_party/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f third_party/grpc/third_party/zlib/CMakeFiles/zlib.dir/build.make third_party/grpc/third_party/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f third_party/grpc/third_party/zlib/CMakeFiles/example.dir/build.make third_party/grpc/third_party/zlib/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named minigzip

# Build rule for target.
minigzip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minigzip
.PHONY : minigzip

# fast build rule for target.
minigzip/fast:
	$(MAKE) -f third_party/grpc/third_party/zlib/CMakeFiles/minigzip.dir/build.make third_party/grpc/third_party/zlib/CMakeFiles/minigzip.dir/build
.PHONY : minigzip/fast

#=============================================================================
# Target rules for targets named minigzip64

# Build rule for target.
minigzip64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minigzip64
.PHONY : minigzip64

# fast build rule for target.
minigzip64/fast:
	$(MAKE) -f third_party/grpc/third_party/zlib/CMakeFiles/minigzip64.dir/build.make third_party/grpc/third_party/zlib/CMakeFiles/minigzip64.dir/build
.PHONY : minigzip64/fast

#=============================================================================
# Target rules for targets named example64

# Build rule for target.
example64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example64
.PHONY : example64

# fast build rule for target.
example64/fast:
	$(MAKE) -f third_party/grpc/third_party/zlib/CMakeFiles/example64.dir/build.make third_party/grpc/third_party/zlib/CMakeFiles/example64.dir/build
.PHONY : example64/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/main.cpp.s
.PHONY : main.cpp.s

proto-gen/Student.grpc.pb.o: proto-gen/Student.grpc.pb.cc.o

.PHONY : proto-gen/Student.grpc.pb.o

# target to build an object file
proto-gen/Student.grpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/proto-gen/Student.grpc.pb.cc.o
.PHONY : proto-gen/Student.grpc.pb.cc.o

proto-gen/Student.grpc.pb.i: proto-gen/Student.grpc.pb.cc.i

.PHONY : proto-gen/Student.grpc.pb.i

# target to preprocess a source file
proto-gen/Student.grpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/proto-gen/Student.grpc.pb.cc.i
.PHONY : proto-gen/Student.grpc.pb.cc.i

proto-gen/Student.grpc.pb.s: proto-gen/Student.grpc.pb.cc.s

.PHONY : proto-gen/Student.grpc.pb.s

# target to generate assembly for a file
proto-gen/Student.grpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/proto-gen/Student.grpc.pb.cc.s
.PHONY : proto-gen/Student.grpc.pb.cc.s

proto-gen/Student.pb.o: proto-gen/Student.pb.cc.o

.PHONY : proto-gen/Student.pb.o

# target to build an object file
proto-gen/Student.pb.cc.o:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/proto-gen/Student.pb.cc.o
.PHONY : proto-gen/Student.pb.cc.o

proto-gen/Student.pb.i: proto-gen/Student.pb.cc.i

.PHONY : proto-gen/Student.pb.i

# target to preprocess a source file
proto-gen/Student.pb.cc.i:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/proto-gen/Student.pb.cc.i
.PHONY : proto-gen/Student.pb.cc.i

proto-gen/Student.pb.s: proto-gen/Student.pb.cc.s

.PHONY : proto-gen/Student.pb.s

# target to generate assembly for a file
proto-gen/Student.pb.cc.s:
	$(MAKE) -f CMakeFiles/libraft.dir/build.make CMakeFiles/libraft.dir/proto-gen/Student.pb.cc.s
.PHONY : proto-gen/Student.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... libraft"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... tools"
	@echo "... check_epollexclusive"
	@echo "... gen_legal_metadata_characters"
	@echo "... grpcpp_channelz"
	@echo "... grpc++"
	@echo "... upb"
	@echo "... grpc_unsecure"
	@echo "... grpc_print_google_default_creds_token"
	@echo "... grpc_plugin_support"
	@echo "... address_sorting"
	@echo "... grpc_cronet"
	@echo "... grpc++_unsecure"
	@echo "... grpc++_reflection"
	@echo "... grpc_ruby_plugin"
	@echo "... tools_cxx"
	@echo "... gen_hpack_tables"
	@echo "... grpc"
	@echo "... grpc_csharp_ext"
	@echo "... plugins"
	@echo "... grpc++_error_details"
	@echo "... grpc_create_jwt"
	@echo "... gpr"
	@echo "... tools_c"
	@echo "... gen_percent_encoding_tables"
	@echo "... grpc_cpp_plugin"
	@echo "... grpc_csharp_plugin"
	@echo "... grpc_node_plugin"
	@echo "... grpc_objective_c_plugin"
	@echo "... grpc_php_plugin"
	@echo "... grpc_python_plugin"
	@echo "... grpc_verify_jwt"
	@echo "... ahost"
	@echo "... adig"
	@echo "... c-ares"
	@echo "... acountry"
	@echo "... libprotobuf"
	@echo "... protoc"
	@echo "... libprotobuf-lite"
	@echo "... libprotoc"
	@echo "... global_target"
	@echo "... all_tests"
	@echo "... crypto_test_data"
	@echo "... boringssl_gtest"
	@echo "... run_tests"
	@echo "... urandom_test"
	@echo "... crypto"
	@echo "... crypto_test"
	@echo "... fipsmodule"
	@echo "... boringssl_gtest_main"
	@echo "... test_support_lib"
	@echo "... ssl_test"
	@echo "... ssl"
	@echo "... bssl_shim"
	@echo "... handshaker"
	@echo "... bssl"
	@echo "... decrepit_test"
	@echo "... decrepit"
	@echo "... zlibstatic"
	@echo "... zlib"
	@echo "... example"
	@echo "... minigzip"
	@echo "... minigzip64"
	@echo "... example64"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... proto-gen/Student.grpc.pb.o"
	@echo "... proto-gen/Student.grpc.pb.i"
	@echo "... proto-gen/Student.grpc.pb.s"
	@echo "... proto-gen/Student.pb.o"
	@echo "... proto-gen/Student.pb.i"
	@echo "... proto-gen/Student.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

