// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Student.proto

#include "Student.pb.h"
#include "Student.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace student {

static const char* StudentService_method_names[] = {
  "/student.StudentService/sendStudent",
};

std::unique_ptr< StudentService::Stub> StudentService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StudentService::Stub> stub(new StudentService::Stub(channel));
  return stub;
}

StudentService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sendStudent_(StudentService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StudentService::Stub::sendStudent(::grpc::ClientContext* context, const ::student::Student& request, ::student::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sendStudent_, context, request, response);
}

void StudentService::Stub::experimental_async::sendStudent(::grpc::ClientContext* context, const ::student::Student* request, ::student::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendStudent_, context, request, response, std::move(f));
}

void StudentService::Stub::experimental_async::sendStudent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::student::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendStudent_, context, request, response, std::move(f));
}

void StudentService::Stub::experimental_async::sendStudent(::grpc::ClientContext* context, const ::student::Student* request, ::student::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sendStudent_, context, request, response, reactor);
}

void StudentService::Stub::experimental_async::sendStudent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::student::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sendStudent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::student::Reply>* StudentService::Stub::AsyncsendStudentRaw(::grpc::ClientContext* context, const ::student::Student& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::student::Reply>::Create(channel_.get(), cq, rpcmethod_sendStudent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::student::Reply>* StudentService::Stub::PrepareAsyncsendStudentRaw(::grpc::ClientContext* context, const ::student::Student& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::student::Reply>::Create(channel_.get(), cq, rpcmethod_sendStudent_, context, request, false);
}

StudentService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::student::Student, ::student::Reply>(
          std::mem_fn(&StudentService::Service::sendStudent), this)));
}

StudentService::Service::~Service() {
}

::grpc::Status StudentService::Service::sendStudent(::grpc::ServerContext* context, const ::student::Student* request, ::student::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace student

